### ISSUE TITLE
Assessment Results

### ISSUE THREAD

**Issue by timomitchel** [eoneill23/mod_0_skills#1]
# Checklist/Rubric

### Part I: Creating Directories and Files; Initializing Git and Pushing to GitHub

- [x] I named my directories correctly. 
- [x] I named my files correctly.
- [x] I structured my files and directories correctly. 
- [x] I made one initial commit.
- [x] I pushed my initial commit to GitHub.

### Part II: Top Down Design

- [x] I broke down larger processes into smaller layers.
- [x] I added and committed my changes with a properly formatted commit message starting with a verb and a capital letter.
- [x] I pushed my changes to Github. 

### Part III: Classes, Objects, Attributes, and Methods

Class #1 Checklist
- [] I named my class correctly
- [x] I structured and named my directories and files correctly.
- [x] The three attributes I chose for **Class #1** represent properties or characteristics.
- [x] I identified the data type (string, integer, boolean, array, hash/object, datetime) for attributes in **Class 1**.
- [x] The three methods I chose for **Class #1** represent behaviors or actions.
- [x] I described what the methods do in **Class 1**.
- [] I added and committed the `class_1.txt` file **separately** with a properly formatted commit message. 

Class #1 Example Object Checklist
- [x] The object I chose for **Class 1** is an instance of this class. 
- [x] I listed the values for each attribute of this object. 
- [x] I listed the results of each method for this object. 
- [x] I added and committed the `class_1_example_object.txt` file **separately** with a properly formatted commit message. 

Class #2 Checklist
- [x] I named my class correctly
- [x] The three attributes I chose for **Class #2** represent states or characteristics.
- [x] I identified the data type (string, integer, boolean, array, hash/object, datetime) for attributes in **Class 2**.
- [x] The three methods I chose for **Class #2** represent behaviors or actions.
- [x] I described what the methods do in **Class 2**.
- [x] I added and committed the `class_2.txt` file **separately** with a properly formatted commit message. 

Class #2 Example Object Checklist
- [x] I listed the values for each attribute of this object. 
- [x] I listed the results of each method for this object. 
- [x] I added and committed each change **separately** with a properly formatted commit message. 
- [] I added and committed the `class_2_example_object.txt` file **separately** with a properly formatted commit message. 

Assessment Grade
- [] Technical Ready
- [x] Pending
- [] Not Ready

Hey Eric! Good job on your assessment. I know you had some issues so I'm proud of you for reaching out and pushing through them. I want you to make a couple updates to your assessment and then we will update your status. Remember that we name our classes singularly. So go ahead and update the `Meals` class and commit those changes with a properly formatted commit message. We only want to make one `Initial Commit` and then from that point forward we want to describe our changes with each commit message. The `Add_Cheese` method is doing a bit too much. We would only want it to modify one attribute so that our program is more flexible when it inevitably changes. Go ahead and update this method to only modify one attribute. Then commit this change separately with a proper commit message.  Also, try to keep your naming conventions one way and stick with it. If you want to go with `Scheduled_to_work` then make sure all other attributes/methods follow that pattern. Go ahead and make sure all of your naming follows one convention, and commit these changes separately. Send Rachel, Sarah, Katie, and I a DM when you have made these updates. Thanks Eric!
